# Generated by Django 4.0.1 on 2022-01-09 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='images',
            old_name='category',
            new_name='x',
        ),
    ]
